# .github/workflows/update_chunithm_data.yml

name: Update CHUNITHM Data

# このワークフローが実行されるタイミング
on:
  # 1. スケジュール実行: UTCの毎日午前0時に実行 (日本時間では午前9時)
  #    時間は自由に変更してください (cron形式)
  schedule:
    - cron: '0 0,6,12,18'
  
  # 2. 手動実行: GitHubのActionsタブから「Run workflow」ボタンでいつでも実行可能
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest # 実行環境として最新のUbuntuを使用
    steps:
      # 1. リポジトリのコードをチェックアウト(ダウンロード)する
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 使用するPythonのバージョン

      # 3. 必要なPythonライブラリ(requests)をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Pythonスクリプトを実行して chunithm.json を更新
      - name: Run script to update data
        run: python update_data.py # あなたが付けたPythonスクリプトの名前に合わせる

      # 5. 変更があった場合のみ、コミットとプッシュを行う
      - name: Commit and push if there are changes
        run: |
          # Gitのユーザー情報を設定
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 変更をステージング
          git add chunithm.json
          
          # 変更があるかどうかを確認
          if ! git diff --staged --quiet; then
            # 変更があればコミット
            git commit -m "Automated update of chunithm.json"
            # リポジトリにプッシュ
            git push
          else
            # 変更がなければメッセージを表示
            echo "No changes to commit."
          fi
